name: Cache Workflow

on:
  push:
    branches: [ "master" ]   # or "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-b29f931

      - name: prime-cache-b29f931
        run: |
          echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
